version: '3.8'
services:
  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: discord-bot
      POSTGRES_USER: discord-bot
      POSTGRES_DB: discord-bot
    ports:
      - '5432:5432'
    volumes: 
      - ./postgresql:/var/lib/postgresql/data
volumes:
  db:
    driver: local
