version: "3.8"
services:
  dev-db:
    image: postgres:12-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: discord-bot
      POSTGRES_USER: discord-bot
      POSTGRES_DB: discord-bot
